server:
  port: 8080

management:
  server:
    port: 8081

trade-service:
  matching:
    missing-product-productname-placeholder: Missing Product Name

logging:
  level:
    com.example.tradeservice: INFO

