server:
  port: 8080
#  tomcat:
#    max-swallow-size: 300MB
#    max-http-form-post-size: 300MB

management:
  server:
    port: 8081

trade-service:
  matching:
    missing-product-productname-placeholder: Missing Product Name

logging:
  level:
    com.example.tradeservice: INFO
