# curl -F 'file=@trade.csv' --request POST http://localhost:8080/api/v1/enrich
POST http://localhost:8080/api/v1/enrich
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="trade.csv"

< trade.csv
--WebAppBoundary--

###
